version: "3"
services:
  app:
    build: .
    container_name: todos-vanilla
    volumes:
      - .:/app
    ports:
      - "1234:1234"
      - "1235:1235"
    command: parcel --hmr-port 1235 --hmr-hostname localhost src/index.pug

